name: Deploy weather app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Init project
        uses: actions/checkout@v2
      - name: JS Linter
        uses: actions/javascript-action@v1
        with:
          milliseconds: 1000
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP}}